name: End-to-end tests

on:
  push:
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:cloud
        env:
          CYPRESS_URL_HTTPS_AKTIAN: ${{ vars.URL_HTTPS_AKTIAN }}
          CYPRESS_USER_AKTIAN: ${{ secrets.USER_AKTIAN }}
          CYPRESS_PASSWORD_USER_AKTIAN: ${{ secrets.PASSWORD_USER_AKTIAN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ vars.CYPRESS_PROJECT_ID }}
